version: 2
updates:
  - package-ecosystem: "uv" # See documentation for possible values
    versioning-strategy: widen
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
