"""PFS constants moved out of psf.py to keep the module smaller.

This file contains only constant definitions used across the package.
"""

PFS_MAGIC = 20130315
PFS_VERSION_PS4 = 1
PFS_VERSION_PS5 = 2
PFS_VERSION = PFS_VERSION_PS5
PFS_MODE_SIGNED = 0x1
PFS_MODE_64BIT_INODES = 0x2
PFS_MODE_ENCRYPTED = 0x4
PFS_MODE_CASE_INSENSITIVE = 0x8

INODE_MODE_O_READ = 0x001
INODE_MODE_O_WRITE = 0x002
INODE_MODE_O_EXEC = 0x004
INODE_MODE_G_READ = 0x008
INODE_MODE_G_WRITE = 0x010
INODE_MODE_G_EXEC = 0x020
INODE_MODE_U_READ = 0x040
INODE_MODE_U_WRITE = 0x080
INODE_MODE_U_EXEC = 0x100
INODE_MODE_DIR = 0x4000
INODE_MODE_FILE = 0x8000
INODE_MODE_ANY_WRITE = INODE_MODE_O_WRITE | INODE_MODE_G_WRITE | INODE_MODE_U_WRITE
INODE_RX_ONLY = (
    INODE_MODE_O_READ
    | INODE_MODE_O_EXEC
    | INODE_MODE_G_READ
    | INODE_MODE_G_EXEC
    | INODE_MODE_U_READ
    | INODE_MODE_U_EXEC
)

INODE_FLAG_COMPRESSED = 0x1
INODE_FLAG_READONLY = 0x10
INODE_FLAG_INTERNAL = 0x20000

DIRENT_TYPE_FILE = 2
DIRENT_TYPE_DIRECTORY = 3
DIRENT_TYPE_DOT = 4
DIRENT_TYPE_DOTDOT = 5

INODE_D32_SIZE = 0xA8
INODE_S32_SIZE = 0x2C8
INODE_S64_SIZE = 0x310
MAX_DIRECT_BLOCKS = 12
MAX_INDIRECT_BLOCKS = 5
SIG_SIZE = 32
SIG_ENTRY_S32_SIZE = SIG_SIZE + 4
SIG_ENTRY_S64_SIZE = SIG_SIZE + 8
SIG_ENTRY_SIZE = SIG_ENTRY_S32_SIZE
PFS_XTS_SECTOR_SIZE = 0x1000
UINT32_MAX = 0xFFFFFFFF
INT32_MAX = 0x7FFFFFFF
INODE_FLAG_SIGNED_EXTRA = 0x4 | 0x8
ZERO_EKPFS = b"\x00" * 32
ZERO_PFS_SEED = b"\x00" * 16
HEADER_DIGEST_OFFSET = 0x380
HEADER_DIGEST_SIZE = 0x5A0
PFSC_MAGIC = 0x43534650
PFSC_UNK4 = 0
PFSC_UNK8 = 6
PFSC_LOGICAL_BLOCK_SIZE = 0x10000
PFSC_HEADER_SIZE = 0x30
PFSC_OFFSET_ENTRY_SIZE = 0x8
PFSC_BLOCK_OFFSETS_OFFSET = 0x400
PFSC_INITIAL_DATA_OFFSET = 0x10000
PFSC_INITIAL_OFFSET_TABLE_CAPACITY = PFSC_INITIAL_DATA_OFFSET - PFSC_BLOCK_OFFSETS_OFFSET
